version: '3.8'

services:
  # Base de datos exclusiva para el microservicio de Proyectos
  project-db:
    image: postgres:15-alpine
    container_name: innovatech_project_db
    environment:
      POSTGRES_DB: innovatech_projects
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432" # Mapeamos al 5433 porque el 5432 parece estar ocupado en tu PC
    volumes:
      - project_db_data:/var/lib/postgresql/data
    networks:
      - innovatech-network

  # Base de datos exclusiva para el microservicio de Recursos
  resource-db:
    image: postgres:15-alpine
    container_name: innovatech_resource_db
    environment:
      POSTGRES_DB: innovatech_resources
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5434:5432" # Mapeamos al 5434 para independizarlo completamente
    volumes:
      - resource_db_data:/var/lib/postgresql/data
    networks:
      - innovatech-network

  # Interfaz gráfica para administrar las bases de datos
  pgadmin:
    image: dpage/pgadmin4
    container_name: innovatech_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@innovatech.cl
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5051:80"
    depends_on:
      - project-db
      - resource-db
    networks:
      - innovatech-network

volumes:
  project_db_data:
  resource_db_data:

networks:
  innovatech-network:
    driver: bridge
