
# Habilitar la consola
spring.h2.console.enabled=true
# Definir una URL fija para que no cambie en cada reinicio
spring.datasource.url=jdbc:h2:mem:testdb
# Credenciales simples para el login
spring.datasource.username=sa
spring.datasource.password=password
# (Opcional) Esto ayuda a que veas las sentencias SQL en la terminal
spring.jpa.show-sql=true




spring.application.name=innovatech-project-management-microservice
server.port=8081
